import type {Config} from 'tailwindcss';

const config = {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        body: ['"PT Sans"', 'sans-serif'],
        headline: ['"Playfair Display"', 'serif'],
        code: ['monospace'],
      },
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
       keyframes: {
        'accordion-down': {
          from: {
            height: '0',
          },
          to: {
            height: 'var(--radix-accordion-content-height)',
          },
        },
        'accordion-up': {
          from: {
            height: 'var(--radix-accordion-content-height)',
          },
          to: {
            height: '0',
          },
        },
        'fade-in-up': {
          '0%': {
            opacity: '0',
            transform: 'translateY(20px)',
          },
          '100%': {
            opacity: '1',
            transform: 'translateY(0)',
          },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-in-up': 'fade-in-up 0.5s ease-out forwards',
      },
    },
  },
  plugins: [require('tailwindcss-animate'), require('daisyui')],
  daisyui: {
    themes: [
      {
        light: {
          ...require('daisyui/src/theming/themes')['light'],
          primary: '#16A38B',
          'primary-foreground': '#FFFFFF',
          secondary: '#F0FDF9',
          'secondary-foreground': '#1E40AF',
          accent: '#86EFAC',
          'accent-foreground': '#1E40AF',
          background: '#F0FDF9',
          foreground: '#020617',
          border: '#86EFAC',
          ring: '#16A38B',
          '--radius': '0.5rem',
        },
        dark: {
          ...require('daisyui/src/theming/themes')['dark'],
          primary: '#16A38B',
          'primary-foreground': '#FFFFFF',
          secondary: '#020617',
          'secondary-foreground': '#F0FDF9',
          accent: '#86EFAC',
          'accent-foreground': '#020617',
          background: '#020617',
          foreground: '#F0FDF9',
          border: '#1E40AF',
          ring: '#16A38B',
          '--radius': '0.5rem',
        },
        'Teal Tranquility': {
          primary: 'hsl(175, 55%, 45%)',
          secondary: 'hsl(175, 30%, 95%)',
          accent: 'hsl(175, 55%, 65%)',
          neutral: 'hsl(210, 10%, 45%)',
          'base-100': 'hsl(0, 0%, 100%)',
          info: 'hsl(200, 80%, 50%)',
          success: 'hsl(150, 60%, 45%)',
          warning: 'hsl(45, 90%, 55%)',
          error: 'hsl(0, 70%, 55%)',
        },
        'Ruby Radiance': {
          primary: 'hsl(340, 65%, 50%)',
          secondary: 'hsl(340, 30%, 95%)',
          accent: 'hsl(340, 65%, 70%)',
          neutral: 'hsl(220, 10%, 45%)',
          'base-100': 'hsl(0, 0%, 100%)',
          info: 'hsl(200, 80%, 50%)',
          success: 'hsl(150, 60%, 45%)',
          warning: 'hsl(45, 90%, 55%)',
          error: 'hsl(0, 70%, 55%)',
        },
        'Amber Ambience': {
          primary: 'hsl(40, 90%, 50%)',
          secondary: 'hsl(40, 30%, 95%)',
          accent: 'hsl(40, 90%, 70%)',
          neutral: 'hsl(210, 10%, 45%)',
          'base-100': 'hsl(0, 0%, 100%)',
          info: 'hsl(200, 80%, 50%)',
          success: 'hsl(150, 60%, 45%)',
          warning: 'hsl(45, 90%, 55%)',
          error: 'hsl(0, 70%, 55%)',
        },
        'Emerald Elegance': {
          primary: 'hsl(150, 55%, 45%)',
          secondary: 'hsl(150, 30%, 95%)',
          accent: 'hsl(150, 55%, 65%)',
          neutral: 'hsl(210, 10%, 45%)',
          'base-100': 'hsl(0, 0%, 100%)',
          info: 'hsl(200, 80%, 50%)',
          success: 'hsl(150, 60%, 45%)',
          warning: 'hsl(45, 90%, 55%)',
          error: 'hsl(0, 70%, 55%)',
        },
        'Sapphire Serenity': {
          primary: 'hsl(220, 65%, 55%)',
          secondary: 'hsl(220, 30%, 95%)',
          accent: 'hsl(220, 65%, 75%)',
          neutral: 'hsl(210, 10%, 45%)',
          'base-100': 'hsl(0, 0%, 100%)',
          info: 'hsl(200, 80%, 50%)',
          success: 'hsl(150, 60%, 45%)',
          warning: 'hsl(45, 90%, 55%)',
          error: 'hsl(0, 70%, 55%)',
        },
      },
      'cupcake',
      'bumblebee',
      'corporate',
      'synthwave',
      'retro',
      'cyberpunk',
      'valentine',
      'halloween',
      'garden',
      'forest',
      'aqua',
      'lofi',
      'pastel',
      'fantasy',
      'wireframe',
      'black',
      'luxury',
      'dracula',
      'cmyk',
      'autumn',
      'business',
      'acid',
      'lemonade',
      'night',
      'coffee',
      'winter',
    ],
  },
} satisfies Config;

export default config;
